language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r python/test_requirements.txt --use-mirrors
compiler:
  - gcc
  - clang
script: ./run_tests.sh
env:
  - USE_CLANG_COMPLETER="true"
  - USE_CLANG_COMPLETER="false"
